server:
  port: 8083
spring:
  application:
    name: MENUSERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/menus
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 300000
      leak-detection-threshold: 300000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
    instance:
      prefer-ip-address: true
    client:
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8080/eureka


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: always


resilience4j:
  circuitbreaker:
    instances:
      restaurantBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

