razorpay:
  api-key: "rzp_test_L9MIa55FOxKx7p"
  secret-key: "yXZIVdNRFZUnwXxhugEUP2g1"

server:
  port: 8084

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/payment_service
  application:
    name: PAYMENTSERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8080/eureka



